### ISSUE TITLE
No news with viewport width = 768px

### ISSUE THREAD

**Issue by lesander** [nognooitmeegemaakt/website#2]
No news viewable with a viewport width of exactly `768` pixels.
![](https://puu.sh/q7iO6/5286beac40.jpg)

**Comment by jessevdp** [comment]
**Text just kind of disappears, seems to be too large** 


![capture](https://cloud.githubusercontent.com/assets/15139826/21722343/755713d2-d42c-11e6-82d4-29755dea45f8.PNG)

**Comment by lesander** [comment]
We should use [Shave.js](https://dollarshaveclub.github.io/shave/)

**Comment by lesander** [comment]
Fixed.
