### ISSUE TITLE
facebook button weird display

### ISSUE THREAD

**Issue by jessevdp** [nognooitmeegemaakt/website#5]
![capture](https://cloud.githubusercontent.com/assets/15139826/21722532/57621c22-d42d-11e6-9562-f8939d855f10.PNG)

**Comment by lesander** [comment]
Still applies to the contact area.
![screen shot 2017-01-06 at 17 59 38](https://cloud.githubusercontent.com/assets/4174509/21725723/efac1ba2-d439-11e6-9a13-5bdfda1c8da0.png)

**Comment by jessevdp** [comment]
Oeps, class `news-fb > a` was edited. But this is not the news page..

**Comment by lesander** [comment]
fixed in #8.
